### ISSUE TITLE
[bug] s3 upload failed error

### ISSUE THREAD

**Issue by shunkakinoki** [bridgecrewio/bridgecrew-action#2]
``boto3.exceptions.S3UploadFailedError: Failed to upload ...
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied``

this often occurs while scanning the directory, should I file this issue on the 
https://github.com/bridgecrewio/checkov
page?

**Comment by schosterbarak** [comment]
hey @shunkakinoki  - this might have happened due to wrong format of the repository field.
@jonnyCodev  have just added a validation to the cli command [here](https://github.com/bridgecrewio/checkov/commit/5263b4f099891d1f7249f0e2d6d9e5db13f50ece) at the latest version. would you be able to try again?

**Comment by shunkakinoki** [comment]
Hi @schosterbarak thanks I think it works right now!

**Comment by schosterbarak** [comment]
yes it should! any chance we can do a quick zoom session to understand what is missing? what is your email address?

**Comment by shunkakinoki** [comment]
I wouldn't want a zoom session but a quick support would be nice!
